package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// Manager handles configuration loading, saving, and validation. All reads and
// writes go through the tag-driven registry (registry.go) — the file, the env,
// and `config set` share one parse path, so a key that loads is a key that is
// wired.
type Manager struct {
	configPath string
	config     *Config
}

// NewManager creates a new configuration manager
func NewManager(configPath string) *Manager {
	if configPath == "" {
		configPath = DefaultConfigPath()
	}
	return &Manager{
		configPath: configPath,
		config:     DefaultConfig(),
	}
}

// DefaultConfigPath returns the default configuration file path
func DefaultConfigPath() string {
	return expandPath(DefaultConfigRelativePath)
}

// Load loads configuration from file, returns error if file doesn't exist.
// Environment overrides (GUARDIAN_*) are applied on top of the file values.
func (m *Manager) Load() error {
	if _, err := os.Stat(m.configPath); os.IsNotExist(err) {
		return fmt.Errorf("configuration file not found at %s. Run 'guardiand config init' to create it", m.configPath)
	}

	data, err := os.ReadFile(m.configPath)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	raw := map[string]any{}
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("failed to parse config file: %w", err)
	}

	config := DefaultConfig()
	for key, value := range raw {
		if findFieldSpec(key) == nil {
			// Unknown keys are ignored (old schemas carry retired keys like
			// timeflared_binary); they disappear on the next Save.
			continue
		}
		if err := config.SetField(key, fmt.Sprintf("%v", value)); err != nil {
			return fmt.Errorf("config file %s: %w", m.configPath, err)
		}
	}

	if err := config.ApplyEnvOverrides(); err != nil {
		return fmt.Errorf("environment override: %w", err)
	}

	m.config = config
	return nil
}

// LoadOrDefault loads configuration from file, or returns default config
// (plus env overrides) if the file doesn't exist.
func (m *Manager) LoadOrDefault() error {
	if _, err := os.Stat(m.configPath); os.IsNotExist(err) {
		m.config = DefaultConfig()
		return m.config.ApplyEnvOverrides()
	}
	return m.Load()
}

// Save writes the current configuration as documented YAML. The document is
// generated from the registry, so the file and the schema cannot drift.
func (m *Manager) Save() error {
	configDir := filepath.Dir(m.configPath)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	data := m.generateDocumentedConfig()

	if err := os.WriteFile(m.configPath, []byte(data), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// generateDocumentedConfig renders the config as grouped, commented YAML
// straight from the field registry.
func (m *Manager) generateDocumentedConfig() string {
	var b strings.Builder
	b.WriteString("# Timeflare Guardian Configuration\n")
	b.WriteString("# Generated by guardiand — every key can also be set via `guardiand config set <key> <value>`\n")
	b.WriteString("# or overridden with a GUARDIAN_<KEY> environment variable (flags > env > file > defaults).\n")

	for _, group := range groupOrder {
		fmt.Fprintf(&b, "\n# ================================================================\n# %s\n# ================================================================\n", strings.ToUpper(group))
		for _, spec := range fieldSpecs {
			if spec.Group != group {
				continue
			}
			fmt.Fprintf(&b, "\n# %s\n%s: %s\n", spec.Description, spec.Key, yamlScalar(spec.get(m.config)))
		}
	}
	return b.String()
}

// yamlScalar quotes a value when YAML would otherwise mangle or retype it.
func yamlScalar(v string) string {
	if v == "" {
		return `""`
	}
	// Quote anything that YAML could parse as a non-string when the field is a
	// string, or that contains characters needing escaping. Numbers, booleans
	// and durations round-trip through the registry's string parsing either
	// way, so over-quoting is harmless.
	if strings.ContainsAny(v, ":#{}[]&*!|>'\"%@`") || strings.Contains(v, " ") {
		return fmt.Sprintf("%q", v)
	}
	return v
}

// Get returns the value of a configuration key
func (m *Manager) Get(key string) (string, error) {
	return m.config.GetField(key)
}

// Set sets the value of a configuration key
func (m *Manager) Set(key, value string) error {
	return m.config.SetField(key, value)
}

// SetWithoutValidation is retained for the init flow; the registry's parse
// step always applies (types must hold), only value-level checks are relaxed.
func (m *Manager) SetWithoutValidation(key, value string) error {
	spec := findFieldSpec(key)
	if spec == nil {
		return fmt.Errorf("unknown configuration key: %s", key)
	}
	return spec.set(m.config, value)
}

// GetConfig returns the current configuration
func (m *Manager) GetConfig() *Config {
	// Return a shallow copy to prevent external modification of the manager's
	// view; the cached encryption key pointer is intentionally shared.
	configCopy := *m.config
	return &configCopy
}

// GetConfigPath returns the configuration file path
func (m *Manager) GetConfigPath() string {
	return m.configPath
}

// GetConfigDirectory returns the directory containing the config file
func (m *Manager) GetConfigDirectory() string {
	return filepath.Dir(m.configPath)
}

// GetKeyDirectory returns the directory where keys should be stored
// This defaults to the same directory as the config file for custom paths,
// or uses the keyring_dir config value if set, or falls back to config directory
func (m *Manager) GetKeyDirectory() string {
	// If keyring_dir is explicitly set in config and not the default, use it
	if m.config.KeyringDir != "" && m.config.KeyringDir != expandPath(DefaultGuardianDir) {
		return m.config.KeyringDir
	}

	// For custom config paths, default to same directory as config
	configDir := m.GetConfigDirectory()
	defaultConfigDir := filepath.Dir(expandPath(DefaultConfigRelativePath))

	if configDir != defaultConfigDir {
		return configDir
	}

	// For default config path, use the configured keyring dir or default
	if m.config.KeyringDir != "" {
		return m.config.KeyringDir
	}

	return expandPath(DefaultGuardianDir)
}

// GetPrivateKeyPath returns the path where the private key should be stored
func (m *Manager) GetPrivateKeyPath() string {
	// If explicitly set in config, use that
	if m.config.EncryptionPrivateKeyPath != "" {
		defaultPath := expandPath(DefaultGuardianDir + "/" + DefaultPrivateKeyFileName)
		if m.config.EncryptionPrivateKeyPath != defaultPath {
			return m.config.EncryptionPrivateKeyPath
		}
	}

	// Otherwise derive from key directory
	return filepath.Join(m.GetKeyDirectory(), DefaultPrivateKeyFileName)
}

// GetPublicKeyPath returns the path where the public key should be stored
func (m *Manager) GetPublicKeyPath() string {
	return filepath.Join(m.GetKeyDirectory(), DefaultPublicKeyFileName)
}

// EnsureDirectoriesExist creates the necessary directories for config and keys
func (m *Manager) EnsureDirectoriesExist() error {
	configDir := m.GetConfigDirectory()
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory %s: %w", configDir, err)
	}

	keyDir := m.GetKeyDirectory()
	if err := os.MkdirAll(keyDir, 0755); err != nil {
		return fmt.Errorf("failed to create key directory %s: %w", keyDir, err)
	}

	return nil
}

// ConfigItem represents a configuration item with value and description
type ConfigItem struct {
	Value       string
	Description string
	IsDefault   bool
}

// ListAllGrouped returns configuration parameters organised by their tag
// group, with default-difference marking for `config list`.
func (m *Manager) ListAllGrouped() map[string]map[string]ConfigItem {
	defaults := DefaultConfig()
	groups := make(map[string]map[string]ConfigItem, len(groupOrder))
	for _, spec := range fieldSpecs {
		if groups[spec.Group] == nil {
			groups[spec.Group] = make(map[string]ConfigItem)
		}
		groups[spec.Group][spec.Key] = ConfigItem{
			Value:       spec.display(m.config),
			Description: spec.Description,
			// Compared on the stored value, not the displayed one: two
			// different hashes are both "set" and both differ from the default.
			IsDefault: spec.get(m.config) == spec.get(defaults),
		}
	}
	return groups
}

// GroupOrder returns the display order of config groups.
func GroupOrder() []string {
	out := make([]string, len(groupOrder))
	copy(out, groupOrder)
	return out
}

// Validate validates the current configuration
func (m *Manager) Validate() error {
	return m.config.Validate()
}
