package custody

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// PassphraseFileName is the conventional name of the share-key passphrase
// file when it sits beside the private key file. When the configured
// passphrase path is absent (e.g. a container whose config carries paths from
// an init environment), the loader falls back to this sibling of the — env
// overridable — private key path, so the pair travels as one unit on a
// volume.
const PassphraseFileName = "encryption_key_passphrase"

// shareKeySize is the raw X25519 private scalar length; a file of exactly
// this size is the legacy plaintext format.
const shareKeySize = 32

// LoadShareKey loads the guardian's X25519 share-encryption private key from
// path. Both formats are readable: the versioned encrypted envelope
// (generated by default) and the legacy raw 32-byte plaintext file (migrate
// with `guardiand config migrate-key`). passphrase is consulted lazily —
// plaintext files never require one.
func LoadShareKey(path string, passphrase func() (string, error)) ([32]byte, error) {
	var key [32]byte

	data, err := os.ReadFile(path)
	if err != nil {
		return key, fmt.Errorf("failed to read private key from %s: %w", path, err)
	}
	defer Zero(data)

	switch {
	case IsEnvelope(data):
		pass, err := passphrase()
		if err != nil {
			return key, fmt.Errorf("private key at %s is encrypted: %w", path, err)
		}
		payload, err := Open(data, pass)
		if err != nil {
			return key, fmt.Errorf("private key at %s: %w", path, err)
		}
		defer Zero(payload)
		if len(payload) != shareKeySize {
			return key, fmt.Errorf("invalid decrypted key length: expected %d bytes, got %d", shareKeySize, len(payload))
		}
		copy(key[:], payload)
		return key, nil

	case len(data) == shareKeySize:
		// Legacy plaintext format — still readable so existing guardians keep
		// running, but generation always encrypts.
		copy(key[:], data)
		return key, nil

	default:
		return key, fmt.Errorf("invalid private key file %s: neither an encrypted envelope nor a raw %d-byte key (got %d bytes)", path, shareKeySize, len(data))
	}
}

// EpochKeyPath is the conventional on-disk location of a RETIRED key epoch:
// the current epoch's key lives at the configured private-key path, and each
// retired epoch N sits beside it as <path>.epoch<N> (same encrypted envelope
// format, same passphrase resolution). `guardiand rotate-key` maintains the
// layout; a retired key is eligible for deletion once its last assignment
// settles (see docs/guides/GUARDIAN_KEY_CUSTODY.md).
func EpochKeyPath(keyPath string, epoch uint64) string {
	return fmt.Sprintf("%s.epoch%d", keyPath, epoch)
}

// SaveEncryptedShareKey writes the key at path as an encrypted envelope with
// 0600 permissions, atomically (temp file + rename) so a crash never leaves a
// partial key file.
func SaveEncryptedShareKey(path string, key [32]byte, passphrase string) error {
	blob, err := Seal(key[:], passphrase)
	if err != nil {
		return fmt.Errorf("failed to encrypt private key: %w", err)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, blob, 0600); err != nil {
		return fmt.Errorf("failed to write encrypted private key: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("failed to move encrypted private key into place: %w", err)
	}
	return nil
}

// IsEncryptedKeyFile reports whether the file at path is an encrypted
// envelope (as opposed to legacy plaintext or garbage).
func IsEncryptedKeyFile(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	defer Zero(data)
	return IsEnvelope(data), nil
}

// ResolvePassphrasePath returns the passphrase file to use for the key at
// keyPath: the configured path when it exists, otherwise the conventional
// sibling of the key file. Returns an error naming both candidates when
// neither exists.
func ResolvePassphrasePath(configured, keyPath string) (string, error) {
	if configured != "" {
		if _, err := os.Stat(configured); err == nil {
			return configured, nil
		}
	}
	sibling := SiblingPassphrasePath(keyPath)
	if _, err := os.Stat(sibling); err == nil {
		return sibling, nil
	}
	if configured != "" {
		return "", fmt.Errorf("no passphrase file found (configured %s and sibling %s both missing)", configured, sibling)
	}
	return "", fmt.Errorf("no passphrase file found (encryption_key_passphrase not set and sibling %s missing)", sibling)
}

// SiblingPassphrasePath is the conventional passphrase file location for a
// given private key path.
func SiblingPassphrasePath(keyPath string) string {
	return filepath.Join(filepath.Dir(keyPath), PassphraseFileName)
}

// ReadPassphraseFile reads a passphrase from a file: the file content IS the
// passphrase, verbatim, with surrounding whitespace trimmed. Never decoded —
// a base64 guess here once silently mangled any raw passphrase that happened
// to parse as base64 (guardian sweep finding 30). The file's 0600 mode is
// the control; encoding was only ever obscurity.
func ReadPassphraseFile(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read passphrase file: %w", err)
	}
	return strings.TrimSpace(string(raw)), nil
}

// WritePassphraseFile stores a passphrase verbatim with 0600 permissions —
// the exact bytes ReadPassphraseFile returns.
func WritePassphraseFile(path, passphrase string) error {
	if err := os.WriteFile(path, []byte(passphrase), 0600); err != nil {
		return fmt.Errorf("failed to write passphrase file: %w", err)
	}
	return nil
}

// FilePassphrase returns a lazy passphrase supplier for LoadShareKey that
// resolves the passphrase file (configured or sibling) and reads it.
func FilePassphrase(configured, keyPath string) func() (string, error) {
	return func() (string, error) {
		path, err := ResolvePassphrasePath(configured, keyPath)
		if err != nil {
			return "", err
		}
		return ReadPassphraseFile(path)
	}
}
